%define GDT_ENTRY_SIZE 8

%define GDT_TI 0
%define LDT_TI 1


; creates selector field
; RPL is the requested privelege level
; TI is the Table Index, defined above
; INDEX is the index of the descriptor in said table
%define SELECTOR(RPL, TI, INDEX) RPL | TI << 2 | INDEX << 3

; For our kernel only
%define GDT_SELECTOR_NULL  SELECTOR(0, GDT_TI, 0)
%define GDT_SELECTOR_KCODE SELECTOR(0, GDT_TI, 1)
%define GDT_SELECTOR_KDATA SELECTOR(0, GDT_TI, 2)
