DWORD_SIZE equ 4

%define arg(x) ebp + (x+2)*DWORD_SIZE 

; Preserves base pointer and sets it
%macro proc 0
  push ebp 
  mov ebp, esp 
%endmacro

; Ends procedure and returns
%macro endproc 0
  pop ebp ; restore base pointer
  ret
%endmacro

; better syntax for c function calls
%macro ccall 2-*                        
%define _j %1
%assign __params %0-1
%rep %0-1
    %rotate -1
    push %1
%endrep
    call _j
    %assign __params __params * 4
    add esp, __params
%endmacro

