global VGA_COLOR_BLACK
global VGA_COLOR_BLUE 
global VGA_COLOR_GREEN
global VGA_COLOR_CYAN 
global VGA_COLOR_RED
global VGA_COLOR_MAGENTA
global VGA_COLOR_BROWN
global VGA_COLOR_LIGHT_GREY 
global VGA_COLOR_DARK_GREY
global VGA_COLOR_LIGHT_BLUE 
global VGA_COLOR_LIGHT_GREEN  
global VGA_COLOR_LIGHT_CYAN  
global VGA_COLOR_LIGHT_RED  
global VGA_COLOR_LIGHT_MAGENTA  
global VGA_COLOR_LIGHT_BROWN  
global VGA_COLOR_WHITE 

global VGA_XSIZE 
global VGA_YSIZE 
global VGA_BUFFER_ADDR

; Declare VGA color consts
VGA_COLOR_BLACK  equ 0
VGA_COLOR_BLUE  equ 1
VGA_COLOR_GREEN  equ 2
VGA_COLOR_CYAN  equ 3
VGA_COLOR_RED  equ 4
VGA_COLOR_MAGENTA  equ 5
VGA_COLOR_BROWN  equ 6
VGA_COLOR_LIGHT_GREY  equ 7
VGA_COLOR_DARK_GREY  equ 8
VGA_COLOR_LIGHT_BLUE  equ 9
VGA_COLOR_LIGHT_GREEN  equ 10
VGA_COLOR_LIGHT_CYAN  equ 11
VGA_COLOR_LIGHT_RED  equ 12
VGA_COLOR_LIGHT_MAGENTA  equ 13
VGA_COLOR_LIGHT_BROWN  equ 14
VGA_COLOR_WHITE equ 15

VGA_XSIZE equ 80
VGA_YSIZE equ 25
VGA_BUFFER_ADDR equ 0xB8000

